"""empty message

Revision ID: 6955408ab18a
Revises: 3f170f9a28ec
Create Date: 2026-03-21 15:18:58.871281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6955408ab18a'
down_revision = '3f170f9a28ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
